# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "sdl-0.2.4+3.2.16-7uIn9DPhfgH29yAIJqHLc69hNb4IW0q-AngtKCFoT92b";
    path = fetchgit {
      url = "https://github.com/castholm/SDL.git";
      rev = "3ed62e53aecd9ffb28e44b9d35b7c09a8739e823";
      hash = "sha256-ZP/KyRRJda4uTMXiSDKyXhdlppx9vN//PSASm2PuQLo=";
    };
  }
  {
    name = "sdl_linux_deps-0.0.0-Vy5_h4AlfwBtG7MIPe7ZNUANhmYLek_SA140uYk9SrED";
    path = fetchgit {
      url = "https://github.com/castholm/SDL_linux_deps.git";
      rev = "085212f286621835f2638cb0cfff078fe515341a";
      hash = "sha256-2NWnMwJNl7JzSRq6cym1CJjlEDIlDwvWCfbD+Q1Ig4w=";
    };
  }
]